### ISSUE TITLE
BUG: Modin on HDK fails during apply call

### ISSUE THREAD

**Issue by aregm** [intel-ai/hdk#288] opened 2023-03-16 19:44 UTC
Please refer to https://github.com/modin-project/modin/issues/5803 for details.
@alexbaden @ienkovich @Egor-Krivov

**Comment by ienkovich** [comment] 2023-03-16 20:10
`apply` is not supported by HDK backend in Modin, so the problem is on Modin side which is supposed to fallback to Pandas in this case.

**Comment by alexbaden** [comment] 2023-03-16 20:19
I just checked and I suspect this is using an old version of HDK. The provided script executes without errors for me:
```
UserWarning: Distributing <class 'dict'> object. This may take some time.
UserWarning: <function DataFrame.to_numpy> is not currently supported by ExperimentalHdkOnNative, defaulting to pandas implementation.
Please refer to https://modin.readthedocs.io/en/stable/supported_apis/defaulting_to_pandas.html for explanation.
UserWarning: <function DataFrame.applymap> is not currently supported by ExperimentalHdkOnNative, defaulting to pandas implementation.
                         user  new_id
0        HcbGLZEMQnUUOFqdUdOd       0
1        tUSyoVWHpmEeRfjVCupV       1
2        bqmvOSOuJIDnPHHMsjFS       2
3        wIuWfUiOyvBpEvPKfYcC       3
4        REsDBDZavrUblFPStSIG       4
...                       ...     ...
9999995  PEWxuBGSyHVViCRRusRG  999995
9999996  ddntHBhYKqjThPSzodLd  999996
9999997  kzTpMZwkYnDHfzqciXul  999997
9999998  GEUWxFvNJhZdaROcntHW  999998
9999999  iYpAXCwCBFMQPXhciqqX  999999

[10000000 rows x 2 columns]
```
I think that looks reasonable?

**Comment by Garra1980** [comment] 2023-03-21 20:51
also works for me having 
modin-hdk                 0.19.0
pyhdk                     0.4.0 
so probably the problem was in using old versions. I think we can close it

**Closed** 2023-03-23 19:39 UTC
