### ISSUE TITLE
SIGSEGV on join tables

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel-ai/hdk#254] opened 2023-03-03 19:02 UTC
The following modin code:
```python
import modin.pandas as pd
df = pd.DataFrame({"a": [1]})
print(pd.merge(df + 1, df + 2))
```
causes SIGSEGV:
<details>

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1409e7d3b0, pid=133604, tid=133604
#
# JRE version: OpenJDK Runtime Environment (17.0.3) (build 17.0.3-internal+0-adhoc..src)
# Java VM: OpenJDK 64-Bit Server VM (17.0.3-internal+0-adhoc..src, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x27d3b0]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<548964ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 548964ul>::oop_access_barrier(void*)+0x0
```

</details>
Execution tree:
<details>

```
JoinNode:
  Fields:
    a: frame$2.a[int64]
  How: inner
  Condition: (= [frame$2.a[int64], frame$3.a[int64]] [bool])
  input[0]:
    TransformNode:
      a: (+ [frame$1.a[int64], 1[int64]] [int64])
      input[0]: frame$1
  input[1]:
    TransformNode:
      a: (+ [frame$1.a[int64], 2[int64]] [int64])
      input[0]: frame$1
```

</details>

**Comment by ienkovich** [comment] 2023-03-11 03:38
@AndreyPavlenko I couldn't reproduce this error using the latest modin and HDK branches. Could you please confirm that problem still exists? In my run, I see exactly the same execution tree, but the execution is successful and the result matches pandas.

**Comment by Garra1980** [comment] 2023-03-11 03:49
This one is flaky :( I see such error sometimes on different flows

**Comment by ienkovich** [comment] 2023-03-11 04:02
I tried to run it 100 times with no luck to reproduce. IIUC @AndreyPavlenko has a stable failure. In case of flaky failure, I'd like to know the exact revisions for reproduction or probably access to the env where you get this failure.

**Comment by ienkovich** [comment] 2023-03-13 23:23
Working on another issue I accidentally found that using an inexistent table name in JSON RelAlg causes a failure that exactly matches the one in the description.

**Comment by ienkovich** [comment] 2023-03-14 00:19
I also noticed that when this error occurs, Calcite log has a stack trace pointing to the place where `NullPointerException` error occurs.

**Comment by ienkovich** [comment] 2023-03-14 00:51
I created #283 to produce an error for unknown table names in JSON instead of a segfault. But I suppose we might get a similar SIGSEGV message from JVM for all kinds of errors in generated JSON.

@AndreyPavlenko I assign it back to you for now for the help with reproduction. I still can't trigger the error using the provided test. If you can reproduce it, please attach Calcite log (it goes to `hdk_log/log4j.log` by default)

**Comment by AndreyPavlenko** [comment] 2023-03-27 22:56
It's not reproducible on the master branch, but it's 100% reproducible in my env with the following version installed:
```
pyhdk                      0.4.0         py310h1234567_0_cpu  conda-forge
```
Here is the log:
<details>

```java
2023-03-28 00:49:22 ERROR CalciteServerHandler:process:179 - class java.lang.NullPointerException
2023-03-28 00:49:22 ERROR CalciteServerHandler:process:181 - null
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at org.apache.calcite.rex.RexNormalize.normalize(RexNormalize.java:102) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexCall.getNormalized(RexCall.java:275) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexCall.equals(RexCall.java:287) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at java.util.Objects.equals(Objects.java:64) ~[?:?]
        at org.apache.calcite.util.Pair.equals(Pair.java:95) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at java.util.HashMap.getNode(HashMap.java:570) ~[?:?]
        at java.util.HashMap.get(HashMap.java:556) ~[?:?]
        at org.apache.calcite.rex.RexProgramBuilder.registerInternal(RexProgramBuilder.java:343) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder.access$300(RexProgramBuilder.java:43) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder$RegisterShuttle.visitCall(RexProgramBuilder.java:897) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder$RegisterShuttle.visitCall(RexProgramBuilder.java:894) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexCall.accept(RexCall.java:189) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder$RegisterMidputShuttle.visitLocalRef(RexProgramBuilder.java:1016) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder$RegisterMidputShuttle.visitLocalRef(RexProgramBuilder.java:1003) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexLocalRef.accept(RexLocalRef.java:77) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder.<init>(RexProgramBuilder.java:137) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder.create(RexProgramBuilder.java:560) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder.forProgram(RexProgramBuilder.java:486) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder.mergePrograms(RexProgramBuilder.java:778) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rex.RexProgramBuilder.mergePrograms(RexProgramBuilder.java:700) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.rel.rules.JoinProjectTransposeRule.onMatch(JoinProjectTransposeRule.java:241) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:337) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:556) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:420) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepPlanner.executeRuleInstance(HepPlanner.java:243) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepInstruction$RuleInstance$State.execute(HepInstruction.java:178) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepPlanner.lambda$executeProgram$0(HepPlanner.java:211) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:210) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepProgram$State.execute(HepProgram.java:118) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:205) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:191) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.prepare.MapDPlanner.applyOptimizationsRules(MapDPlanner.java:249) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at org.apache.calcite.prepare.MapDPlanner.optimizeRaQuery(MapDPlanner.java:267) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mapd.calcite.parser.MapDParser.optimizeRAQuery(MapDParser.java:207) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mapd.parser.server.CalciteServerHandler.process(CalciteServerHandler.java:156) [calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
```

</details>

**Comment by Garra1980** [comment] 2023-04-03 21:40
Looks like not reproducible anywhere now - let's close and reopen in case we face it again

**Closed by Garra1980** 2023-04-03 21:40 UTC
Labels: customer request, in progress
